export { ThemeProvider } from './ThemeProvider';
export { useTheme } from './theme-context';
export { useThemeSync } from './hooks/useThemeSync';
export { CHAT_BACKGROUNDS } from './constants/chat-backgrounds';
export { COLOR_THEMES } from './constants/color-themes';
export type { ColorThemeId } from './constants/color-themes';
export { THEME_BASES } from './constants/theme-bases';
export type { ThemeBaseId } from './constants/theme-bases';
export type { ThemePalette } from './types';
export { DEFAULT_CHAT_APPEARANCE } from './constants/chat-appearance';
export { toSixDigitHex } from './utils/hex-to-rgba';
export { resolveBubbleStyle } from './utils/resolve-bubble-style';
