export { ThemeProvider } from './ThemeProvider';
export { useTheme } from './theme-context';
export type { ThemeContextValue } from './theme-context';
export { useThemeSync } from './hooks/useThemeSync';
export { mergeTheme } from './merge-theme';
export type { MergedTheme } from './merge-theme';
export { CHAT_BACKGROUNDS } from './constants/chat-backgrounds';
export type { ChatBackground } from './constants/chat-backgrounds';
export { COLOR_THEMES } from './constants/color-themes';
export type { ColorTheme, ColorThemeId } from './constants/color-themes';
export { THEME_BASES } from './constants/theme-bases';
export type { ThemeBase, ThemeBaseId } from './constants/theme-bases';
export type { ThemePalette } from './types';
export { DEFAULT_CHAT_APPEARANCE } from './constants/chat-appearance';
export type { ChatAppearance } from './constants/chat-appearance';
export { getContrastTextColor } from './utils/contrast-text-color';
export { hexToRgba, toSixDigitHex } from './utils/hex-to-rgba';
export { resolveBubbleStyle } from './utils/resolve-bubble-style';
export type { ResolvedBubbleStyle } from './utils/resolve-bubble-style';
